In [20]:
import pandas as pd
import numpy as np

In [21]:
wine = pd.read_csv('wine.csv')
wine

class  Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  \
0        1    14.23        1.71  2.43               15.6        127   
1        1    13.20        1.78  2.14               11.2        100   
2        1    13.16        2.36  2.67               18.6        101   
3        1    14.37        1.95  2.50               16.8        113   
4        1    13.24        2.59  2.87               21.0        118   
..     ...      ...         ...   ...                ...        ...   
173      3    13.71        5.65  2.45               20.5         95   
174      3    13.40        3.91  2.48               23.0        102   
175      3    13.27        4.28  2.26               20.0        120   
176      3    13.17        2.59  2.37               20.0        120   
177      3    14.13        4.10  2.74               24.5         96   

     Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0             2.80        3.06                  0.28             2.29   
1             2.65        2.76                  0.26             1.28   
2             2.80        3.24                  0.30             2.81   
3             3.85        3.49                  0.24             2.18   
4             2.80        2.69                  0.39             1.82   
..             ...         ...                   ...              ...   
173           1.68        0.61                  0.52             1.06   
174           1.80        0.75                  0.43             1.41   
175           1.59        0.69                  0.43             1.35   
176           1.65        0.68                  0.53             1.46   
177           2.05        0.76                  0.56             1.35   

     Color intensity   Hue  OD280/OD315 of diluted wines  Proline  
0               5.64  1.04                          3.92     1065  
1               4.38  1.05                          3.40     1050  
2               5.68  1.03                          3.17     1185  
3               7.80  0.86                          3.45     1480  
4               4.32  1.04                          2.93      735  
..               ...   ...                           ...      ...  
173             7.70  0.64                          1.74      740  
174             7.30  0.70                          1.56      750  
175            10.20  0.59                          1.56      835  
176             9.30  0.60                          1.62      840  
177             9.20  0.61                          1.60      560  

[178 rows x 14 columns]

In [22]:
# import seaborn as sns
# sns.pairplot(wine[list(wine.keys())], hue='class')

# Utilizando SVM

In [23]:
X = wine.iloc[:,1:]
y = wine.iloc[:, 0]

X_teste = X.iloc[177]
X = X.drop(177)
y_teste = y.iloc[177]
y = y.drop(177)

y_teste

3

In [24]:
print(X_teste.shape)
print(np.array(X_teste).reshape(1,-1).shape)

(13,)
(1, 13)


In [25]:
from sklearn.svm import SVC

svc = SVC(kernel='rbf')
svc.fit(X, y)
svc.predict(np.array(X_teste).reshape(1,-1))

C:\Users\jrivo\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([2], dtype=int64)

In [26]:
svc = SVC(kernel='linear')
svc.fit(X, y)
svc.predict(np.array(X_teste).reshape(1,-1))

C:\Users\jrivo\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([3], dtype=int64)

In [27]:
svc = SVC(kernel='poly')
svc.fit(X, y)
svc.predict(np.array(X_teste).reshape(1,-1))

C:\Users\jrivo\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([2], dtype=int64)

In [28]:
svc = SVC(kernel='sigmoid')
svc.fit(X, y)
svc.predict(np.array(X_teste).reshape(1,-1))

C:\Users\jrivo\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

# De volta à base Iris

In [29]:
iris = pd.read_csv('iris.csv')
iris

sepal_length   sepal_width   petal_length   petal_width           class
0             5.1           3.5            1.4           0.2     Iris-setosa
1             4.9           3.0            1.4           0.2     Iris-setosa
2             4.7           3.2            1.3           0.2     Iris-setosa
3             4.6           3.1            1.5           0.2     Iris-setosa
4             5.0           3.6            1.4           0.2     Iris-setosa
..            ...           ...            ...           ...             ...
145           6.7           3.0            5.2           2.3  Iris-virginica
146           6.3           2.5            5.0           1.9  Iris-virginica
147           6.5           3.0            5.2           2.0  Iris-virginica
148           6.2           3.4            5.4           2.3  Iris-virginica
149           5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [30]:
list(iris.keys())

['sepal_length', ' sepal_width', ' petal_length', ' petal_width', ' class']

In [31]:
# import seaborn as sns
# sns.pairplot(iris[list(iris.keys())], hue=' class')

In [32]:
X = iris.iloc[:,0:-1]
y = iris.iloc[:, -1]

# Vamos remover 20% do nosso conjunto de treinamento
# E usar como teste do nosso modelo k-NN
list_ids = list(range(len(y)))
ids_test = list(np.random.choice(list_ids, int(len(list_ids)*0.2), replace=False))

print(len(y), len(ids_test))
X_teste = X.iloc[ids_test]
X = X.drop(index=ids_test)
y_teste = y.iloc[ids_test]
y = y.drop(index=ids_test)
print(len(y), len(y_teste))

150 30
120 30


In [33]:
from sklearn.svm import SVC

svc = SVC(kernel='rbf')
svc.fit(X, y)
preds = svc.predict(np.array(X_teste))
for p, gt in zip(preds,y_teste):
    print(f'{p}\t\t{gt}:    \t{p==gt}')
acertos = sum(preds == y_teste)
print('Acurácia: ',acertos/len(y_teste)*100,'%')
print('==================')

print(svc.score(X_teste, y_teste))

C:\Users\jrivo\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


Iris-versicolor		Iris-versicolor:    	True
Iris-setosa		Iris-setosa:    	True
Iris-versicolor		Iris-versicolor:    	True
Iris-setosa		Iris-setosa:    	True
Iris-setosa		Iris-setosa:    	True
Iris-setosa		Iris-setosa:    	True
Iris-virginica		Iris-versicolor:    	False
Iris-setosa		Iris-setosa:    	True
Iris-setosa		Iris-setosa:    	True
Iris-virginica		Iris-virginica:    	True
Iris-setosa		Iris-setosa:    	True
Iris-virginica		Iris-virginica:    	True
Iris-versicolor		Iris-versicolor:    	True
Iris-versicolor		Iris-versicolor:    	True
Iris-versicolor		Iris-virginica:    	False
Iris-virginica		Iris-virginica:    	True
Iris-setosa		Iris-setosa:    	True
Iris-setosa		Iris-setosa:    	True
Iris-setosa		Iris-setosa:    	True
Iris-versicolor		Iris-versicolor:    	True
Iris-virginica		Iris-virginica:    	True
Iris-versicolor		Iris-versicolor:    	True
Iris-setosa		Iris-setosa:    	True
Iris-virginica		Iris-virginica:    	True
Iris-setosa		Iris-setosa:    	True
Iris-setosa		Iris-setosa:    	T

In [34]:
svc = SVC(kernel='linear')
svc.fit(X, y)
svc.predict(np.array(X_teste))
preds = svc.predict(np.array(X_teste))
for p, gt in zip(preds,y_teste):
    print(f'{p}\t\t{gt}:    \t{p==gt}')
acertos = sum(preds == y_teste)
print('Acurácia: ',acertos/len(y_teste)*100,'%')
print('==================')

print(svc.score(X_teste, y_teste))

Iris-versicolor		Iris-versicolor:    	True
Iris-setosa		Iris-setosa:    	True
Iris-versicolor		Iris-versicolor:    	True
Iris-setosa		Iris-setosa:    	True
Iris-setosa		Iris-setosa:    	True
Iris-setosa		Iris-setosa:    	True
Iris-virginica		Iris-versicolor:    	False
Iris-setosa		Iris-setosa:    	True
Iris-setosa		Iris-setosa:    	True
Iris-virginica		Iris-virginica:    	True
Iris-setosa		Iris-setosa:    	True
Iris-virginica		Iris-virginica:    	True
Iris-versicolor		Iris-versicolor:    	True
Iris-versicolor		Iris-versicolor:    	True
Iris-virginica		Iris-virginica:    	True
Iris-virginica		Iris-virginica:    	True
Iris-setosa		Iris-setosa:    	True
Iris-setosa		Iris-setosa:    	True
Iris-setosa		Iris-setosa:    	True
Iris-versicolor		Iris-versicolor:    	True
Iris-virginica		Iris-virginica:    	True
Iris-versicolor		Iris-versicolor:    	True
Iris-setosa		Iris-setosa:    	True
Iris-virginica		Iris-virginica:    	True
Iris-setosa		Iris-setosa:    	True
Iris-setosa		Iris-setosa:    	Tru

C:\Users\jrivo\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
C:\Users\jrivo\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [35]:
svc = SVC(kernel='poly')
svc.fit(X, y)
svc.predict(np.array(X_teste))
preds = svc.predict(np.array(X_teste))
for p, gt in zip(preds,y_teste):
    print(f'{p}\t\t{gt}:    \t{p==gt}')
acertos = sum(preds == y_teste)
print('Acurácia: ',acertos/len(y_teste)*100,'%')
print('==================')

print(svc.score(X_teste, y_teste))

Iris-versicolor		Iris-versicolor:    	True
Iris-setosa		Iris-setosa:    	True
Iris-versicolor		Iris-versicolor:    	True
Iris-setosa		Iris-setosa:    	True
Iris-setosa		Iris-setosa:    	True
Iris-setosa		Iris-setosa:    	True
Iris-virginica		Iris-versicolor:    	False
Iris-setosa		Iris-setosa:    	True
Iris-setosa		Iris-setosa:    	True
Iris-virginica		Iris-virginica:    	True
Iris-setosa		Iris-setosa:    	True
Iris-virginica		Iris-virginica:    	True
Iris-versicolor		Iris-versicolor:    	True
Iris-versicolor		Iris-versicolor:    	True
Iris-virginica		Iris-virginica:    	True
Iris-virginica		Iris-virginica:    	True
Iris-setosa		Iris-setosa:    	True
Iris-setosa		Iris-setosa:    	True
Iris-setosa		Iris-setosa:    	True
Iris-versicolor		Iris-versicolor:    	True
Iris-virginica		Iris-virginica:    	True
Iris-versicolor		Iris-versicolor:    	True
Iris-setosa		Iris-setosa:    	True
Iris-virginica		Iris-virginica:    	True
Iris-setosa		Iris-setosa:    	True
Iris-setosa		Iris-setosa:    	Tru

C:\Users\jrivo\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
C:\Users\jrivo\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [36]:
svc = SVC(kernel='sigmoid')
svc.fit(X, y)
svc.predict(np.array(X_teste))
preds = svc.predict(np.array(X_teste))
for p, gt in zip(preds,y_teste):
    print(f'{p}\t\t{gt}:    \t{p==gt}')
acertos = sum(preds == y_teste)
print('Acurácia: ',acertos/len(y_teste)*100,'%')
print('==================')

print(svc.score(X_teste, y_teste))

Iris-virginica		Iris-versicolor:    	False
Iris-virginica		Iris-setosa:    	False
Iris-virginica		Iris-versicolor:    	False
Iris-virginica		Iris-setosa:    	False
Iris-virginica		Iris-setosa:    	False
Iris-virginica		Iris-setosa:    	False
Iris-virginica		Iris-versicolor:    	False
Iris-virginica		Iris-setosa:    	False
Iris-virginica		Iris-setosa:    	False
Iris-virginica		Iris-virginica:    	True
Iris-virginica		Iris-setosa:    	False
Iris-virginica		Iris-virginica:    	True
Iris-virginica		Iris-versicolor:    	False
Iris-virginica		Iris-versicolor:    	False
Iris-virginica		Iris-virginica:    	True
Iris-virginica		Iris-virginica:    	True
Iris-virginica		Iris-setosa:    	False
Iris-virginica		Iris-setosa:    	False
Iris-virginica		Iris-setosa:    	False
Iris-virginica		Iris-versicolor:    	False
Iris-virginica		Iris-virginica:    	True
Iris-virginica		Iris-versicolor:    	False
Iris-virginica		Iris-setosa:    	False
Iris-virginica		Iris-virginica:    	True
Iris-virginica		Iris-set

C:\Users\jrivo\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
C:\Users\jrivo\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
